name: Latest blog post workflow
on:
  schedule:
    - cron: "0 0 * * *" # daily at 00:00 UTC
  workflow_dispatch: # manual run button
permissions:
  contents: write
jobs:
  update-readme-with-blog:
    name: Update README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in blog posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://offering.solutions/feed/"
          user_agent: "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
          accept_header: "text/xml"
